services:
  postgres:
    image: postgres:17
    container_name: flight_booking_postgres
    restart: unless-stopped

    environment:
      POSTGRES_DB: flight_booking
      POSTGRES_USER: flight_user
      POSTGRES_PASSWORD: flight_password

    ports:
      - "5432:5432"

    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: