"""create booking domain tables

Revision ID: e5a9538f0ce3
Revises: e3a9eafcc6dd
Create Date: 2026-10-05 02:34:58.493583

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'e5a9538f0ce3'
down_revision: Union[str, Sequence[str], None] = 'e3a9eafcc6dd'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('flights',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('provider', sa.String(length=50), nullable=False),
    sa.Column('provider_reference', sa.String(length=100), nullable=False),
    sa.Column('flight_number', sa.String(length=50), nullable=False),
    sa.Column('flight_name', sa.String(length=100), nullable=False),
    sa.Column('origin_airport_code', sa.String(length=3), nullable=False),
    sa.Column('origin_airport_name', sa.String(length=150), nullable=False),
    sa.Column('destination_airport_code', sa.String(length=3), nullable=False),
    sa.Column('destination_airport_name', sa.String(length=150), nullable=False),
    sa.Column('departure_datetime', sa.DateTime(timezone=True), nullable=False),
    sa.Column('arrival_datetime', sa.DateTime(timezone=True), nullable=False),
    sa.Column('cabin', sa.String(length=20), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('provider', 'provider_reference', name='uq_flight_provider_reference')
    )
    op.create_table('bookings',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('flight_id', sa.UUID(), nullable=False),
    sa.Column('booking_reference', sa.String(length=50), nullable=False),
    sa.Column('booking_date', sa.DateTime(timezone=True), nullable=False),
    sa.Column('status', sa.Enum('HELD', 'AWAITING_PAYMENT', 'CONFIRMED', name='bookingstatus'), nullable=False),
    sa.Column('total_amount', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('currency', sa.String(length=3), nullable=False),
    sa.Column('payment_required_by', sa.DateTime(timezone=True), nullable=True),
    sa.Column('flight_number', sa.String(length=50), nullable=False),
    sa.Column('flight_name', sa.String(length=100), nullable=False),
    sa.Column('origin_airport_code', sa.String(length=3), nullable=False),
    sa.Column('origin_airport_name', sa.String(length=150), nullable=False),
    sa.Column('destination_airport_code', sa.String(length=3), nullable=False),
    sa.Column('destination_airport_name', sa.String(length=150), nullable=False),
    sa.Column('departure_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('arrival_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('cabin', sa.String(length=20), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['flight_id'], ['flights.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('booking_reference')
    )
    op.create_index('ix_bookings_flight_id', 'bookings', ['flight_id'], unique=False)
    op.create_index('ix_bookings_user_id', 'bookings', ['user_id'], unique=False)
    op.create_table('flight_stops',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('flight_id', sa.UUID(), nullable=False),
    sa.Column('stop_sequence', sa.Integer(), nullable=False),
    sa.Column('airport_code', sa.String(length=3), nullable=False),
    sa.Column('airport_name', sa.String(length=150), nullable=False),
    sa.Column('departure_time', sa.DateTime(timezone=True), nullable=False),
    sa.Column('arrival_time', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['flight_id'], ['flights.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('booking_passengers',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('passenger_id', sa.UUID(), nullable=False),
    sa.Column('booking_id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['booking_id'], ['bookings.id'], ),
    sa.ForeignKeyConstraint(['passenger_id'], ['passengers.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('booking_id', 'passenger_id', name='uq_booking_passenger')
    )
    op.create_index('ix_booking_passengers_booking_id', 'booking_passengers', ['booking_id'], unique=False)
    op.create_index('ix_booking_passengers_passenger_id', 'booking_passengers', ['passenger_id'], unique=False)
    op.create_table('payments',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('booking_id', sa.UUID(), nullable=False),
    sa.Column('provider', sa.String(length=20), nullable=False),
    sa.Column('provider_payment_id', sa.String(length=100), nullable=False),
    sa.Column('amount', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('currency', sa.String(length=3), nullable=False),
    sa.Column('status', sa.Enum('CREATED', 'PENDING', 'PAID', 'FAILED', name='paymentstatus'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['booking_id'], ['bookings.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('provider', 'provider_payment_id', name='uq_payment_provider_payment_id')
    )
    op.create_index('ix_payments_booking_id', 'payments', ['booking_id'], unique=False)
    op.create_table('payment_events',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('payment_id', sa.UUID(), nullable=False),
    sa.Column('provider', sa.String(length=20), nullable=False),
    sa.Column('event_type', sa.String(length=50), nullable=False),
    sa.Column('provider_event_id', sa.String(length=100), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('raw_payload', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['payment_id'], ['payments.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('provider', 'provider_event_id', name='uq_payment_event_provider_event_id')
    )
    op.create_index('ix_payment_events_payment_id', 'payment_events', ['payment_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_payment_events_payment_id', table_name='payment_events')
    op.drop_table('payment_events')
    op.drop_index('ix_payments_booking_id', table_name='payments')
    op.drop_table('payments')
    op.drop_index('ix_booking_passengers_passenger_id', table_name='booking_passengers')
    op.drop_index('ix_booking_passengers_booking_id', table_name='booking_passengers')
    op.drop_table('booking_passengers')
    op.drop_table('flight_stops')
    op.drop_index('ix_bookings_user_id', table_name='bookings')
    op.drop_index('ix_bookings_flight_id', table_name='bookings')
    op.drop_table('bookings')
    op.drop_table('flights')
    # ### end Alembic commands ###
